
package com.training.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWS", targetNamespace = "http://ws.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWS {


    /**
     * 
     * @param surname
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.training.com/", className = "com.training.wsclient.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.training.com/", className = "com.training.wsclient.HelloResponse")
    @Action(input = "http://ws.training.com/MyWS/helloRequest", output = "http://ws.training.com/MyWS/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname);

    /**
     * 
     * @param surname
     * @param name
     * @param age
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "goodbye", targetNamespace = "http://ws.training.com/", className = "com.training.wsclient.Goodbye")
    @ResponseWrapper(localName = "goodbyeResponse", targetNamespace = "http://ws.training.com/", className = "com.training.wsclient.GoodbyeResponse")
    @Action(input = "http://ws.training.com/MyWS/goodbyeRequest", output = "http://ws.training.com/MyWS/goodbyeResponse")
    public String goodbye(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "age", targetNamespace = "")
        int age);

}
