
package com.training.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWSService", targetNamespace = "http://ws.training.com/", wsdlLocation = "http://127.0.0.1/myws?wsdl")
public class MyWSService
    extends Service
{

    private final static URL MYWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWSSERVICE_EXCEPTION;
    private final static QName MYWSSERVICE_QNAME = new QName("http://ws.training.com/", "MyWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/myws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWSSERVICE_WSDL_LOCATION = url;
        MYWSSERVICE_EXCEPTION = e;
    }

    public MyWSService() {
        super(__getWsdlLocation(), MYWSSERVICE_QNAME);
    }

    public MyWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWSSERVICE_QNAME, features);
    }

    public MyWSService(URL wsdlLocation) {
        super(wsdlLocation, MYWSSERVICE_QNAME);
    }

    public MyWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWSSERVICE_QNAME, features);
    }

    public MyWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyWS
     */
    @WebEndpoint(name = "MyWSPort")
    public MyWS getMyWSPort() {
        return super.getPort(new QName("http://ws.training.com/", "MyWSPort"), MyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWS
     */
    @WebEndpoint(name = "MyWSPort")
    public MyWS getMyWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.training.com/", "MyWSPort"), MyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWSSERVICE_EXCEPTION!= null) {
            throw MYWSSERVICE_EXCEPTION;
        }
        return MYWSSERVICE_WSDL_LOCATION;
    }

}
